### ISSUE TITLE
Discussion: CLI

### ISSUE THREAD

**Issue by shuvalov-anton** [shuvalov-anton/textr#1]
subj

**Comment by matmuchrapna** [comment]
how do you plan use it?

**Comment by shuvalov-anton** [comment]
`textr -t quotes < text.md > formatted.md`?

**Comment by shuvalov-anton** [comment]
I'd written `test/bench.js` with similar api just for fun and bench. But, probably, we can reuse it for vim/atom plugins

**Comment by matmuchrapna** [comment]
We need to specify list of plugins and options for them. Currently, I cannot imagine short and good enough cli interface to specify all of requirements

**Comment by shuvalov-anton** [comment]
Probably, bundles is the right way to create complex transformations:

```shell
cat text.md | textr -t textr-typography-bundle > formatted.md
```

**Comment by matmuchrapna** [comment]
maybe these?
```
cat some.txt | textr --locale=en typographic-quotes typographic-copyright typographic-ellipses > formatted.md
```

**Comment by shuvalov-anton** [comment]
we can create haha oficial bundles kinda `typography-bundle` to avoid this verbosed setup with one `-t`. `locale` is awesome, true

**Comment by matmuchrapna** [comment]
as far as typography bundles will still formally be textr plugins, then you suggestion doesn’t conflict with mine:
```
cat some.txt | textr --locale=en typographic-quotes typographic-copyright typographic-ellipses > formatted.md
cat some.txt | textr --locale=en typographic-bundle-for-your-awesome-company > formatted.md
```

**Comment by shuvalov-anton** [comment]
Yep, bundles are just plugins.

**Comment by matmuchrapna** [comment]
I don’t like idea of official bundles. we should avoid situation in which we are creating bundles, which can be considered by somebody as ideal. It’s a trap!
![star_wars_its_a_trap](https://cloud.githubusercontent.com/assets/559321/7181178/c4acfcba-e448-11e4-84ac-0214d046f803.jpg)

**Comment by denysdovhan** [comment]
How about adding `--diff` flag, that will show mistakes between original text and result.

**Comment by iamstarkov** [comment]
i like idea, also think that we should have cli in the first place

**Comment by denysdovhan** [comment]
I'd try to implement CLI. Wait for my pull request. Can I use `minimist` as dependecy? Or should I try to do it without one?

**Comment by iamstarkov** [comment]
use smth you like

**Comment by denysdovhan** [comment]
Or should we create a new package such as `textr-cli` with `minimist` and `diff` as deps and keep `textr` without ones.

**Comment by iamstarkov** [comment]
you are reading my thoughts. yes textr-cli should be separate package

**Comment by denysdovhan** [comment]
nice. I'll notify when it will become ready

**Comment by shuvalov-anton** [comment]
@denysdovhan take a look on https://github.com/shuvalov-anton/textr/blob/master/test/bench.js . I've made sort of cli here.

**Comment by denysdovhan** [comment]
@shuvalov-anton cool, I've seen. I'm gonna use this as example.

**Comment by shuvalov-anton** [comment]
:+1:
