### ISSUE TITLE
release 0.3.0 with new options API

### ISSUE THREAD

**Issue by shuvalov-anton** [shuvalov-anton/textr#12]
With 0.3.0 you can set `textr(defaults)` and `tf.exec(text, options)`. That will be useful for recursive usage `textr` bundles. For example, you can set `{locale: 'ru'}` on the top level of your bundles (with `defaults` or with `exec(t, opts)`).

The other one change is that `options` in the plugins can be used as context-object to pass data between the plugins. That achieved by cloning `defaults` and `options` to new object each times when you execute your trasformation stack. But I don't know use-cases for it. I know only one, but IMHO, it's antipattern:

```js
var tf = textr()
  // set locale dynamically
  .use(function (text, ctx) {
    ctx.locale = navigator.locale;
  })
  .use(quotes)
;
```

**Comment by shuvalov-anton** [comment]
If anyone know good patterns to pass data between the plugins like express's `app.use()`, please tell me about it)

**Comment by shuvalov-anton** [comment]
Probably, the time is now

**Comment by iamstarkov** [comment]
looking forward to 0.4.x
