### ISSUE TITLE
guidelines for plugin creators

### ISSUE THREAD

**Issue by iamstarkov** [shuvalov-anton/textr#13]
### File structure:

* [ ] index.js
* [ ] test.js
* [ ] README.md
* [ ] package.json
* [ ] .travis.yml
* [ ] mocha as tests runner

### README structure:
* [ ] title
* [ ] desc
* [ ] installation instruction
* [ ] usage section with spec from tests
* [ ] and license note

just as sketch proposal. What do you think?

**Comment by vladimirstarkov** [comment]
And no Makefile as requirement to be platform independent

**Comment by shuvalov-anton** [comment]
You missed link to the textr :D

**Comment by shuvalov-anton** [comment]
LGTM, of cource!

**Comment by iamstarkov** [comment]
> 21 days ago 

OMG!

**Comment by shuvalov-anton** [comment]
![687474703a2f2f312e62702e626c6f6773706f742e636f6d2f2d6c695f47716f376e376f452f55626638347434796d7a492f41414141414141414145672f4653525237676f36394e302f73313630302f726573697a6564696d6167652e676966](https://cloud.githubusercontent.com/assets/1410106/7569860/7fff1e4c-f814-11e4-95c6-f77648c634ef.gif)

**Comment by iamstarkov** [comment]
See #17
