### ISSUE TITLE
`locale`

### ISSUE THREAD

**Issue by iamstarkov** [shuvalov-anton/textr#15]
textr should have recommendations about using `locale` variable to help textr’s plugins authors

See
http://github.com/iamstarkov/typographic-quotes
http://github.com/iamstarkov/typographic-quotes-l10n-db
http://github.com/andrepolischuk/typographic-numbers
/cc @andrepolischuk

**Comment by iamstarkov** [comment]
Maybe we should take a look at great projects, which are good enough at l10n

**Comment by iamstarkov** [comment]
For example http://momentjs.com/docs/#/i18n/

**Comment by iamstarkov** [comment]
Any other projects? maybe best practices?

**Comment by andrepolischuk** [comment]
We can use BCP 47 language tag, example https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl#Locale_negotiation

**Comment by iamstarkov** [comment]
I want to gather best l10n approaches from popular projects to decide which one fits our needs better.

**Comment by iamstarkov** [comment]
@andrepolischuk will take a look

**Comment by andrepolischuk** [comment]
Angular support l10n and i18n https://docs.angularjs.org/guide/i18n

**Comment by iamstarkov** [comment]
Please, take a look at commit in the related pr

**Comment by andrepolischuk** [comment]
I agree. I will fix typographic-numbers.

**Comment by shuvalov-anton** [comment]
LGTM, of course :D

**Comment by iamstarkov** [comment]
ruby is also using ISO 639 standard https://github.com/tigrish/iso
