### ISSUE TITLE
update examples to explain partialRight

### ISSUE THREAD

**Issue by shuvalov-anton** [shuvalov-anton/textr#3]

**Comment by shuvalov-anton** [comment]
@matmuchrapna I don't the room for `R.partialRight`, but do you?

**Comment by matmuchrapna** [comment]
don’t sure I understand what you mean

**Comment by shuvalov-anton** [comment]
I meant that I don't know the right place to insert `R. partialRight `example in the readme

**Comment by shuvalov-anton** [comment]
sorry. I'd missed "know" word)

**Comment by matmuchrapna** [comment]
should we? it’s good enough to use simple wrapper function
