### ISSUE TITLE
add badges

### ISSUE THREAD

**Issue by shuvalov-anton** [shuvalov-anton/textr#5]

**Comment by matmuchrapna** [comment]
Coverage! npm version! deps! devDeps!

**Comment by shuvalov-anton** [comment]
I guess that is enough to begin. But PR welcomed :D

**Comment by matmuchrapna** [comment]
take a look in new pull request https://github.com/shuvalov-anton/textr/pull/7/commits

actually in these two commits:
* [🐶 wow badges, so stylish, such svg!](https://github.com/matmuchrapna/textr/commit/21786f53a460038abafa9990e88e0fbd59a3a3ef)
*  [introduce coverage reports 🎁](https://github.com/matmuchrapna/textr/commit/23c867d77f32ab032c65a353b2c7f4d0a68d77e8)
