### ISSUE TITLE
improving tests

### ISSUE THREAD

**Issue by matmuchrapna** [shuvalov-anton/textr#8]
current tests are testing concrete plugins, which is redundant plugins are full tested by it’s own, thats why I suggest that textr need more generic way of testing workflow itself and not implementations in terms of concrete plugins

**Comment by shuvalov-anton** [comment]
Yes, you're right. I can replace all tests with one simple test like this:

```js
textr().use(text => '!!!' + text + '!!!');
textr('message').should.be.equal('!!!message!!!')
```

**Comment by matmuchrapna** [comment]
also tests should cover proper order of plugins
